### ISSUE TITLE
docs added to .gitignore

### ISSUE THREAD

**Issue by adrianbj** [rolandtoth/TemplateLatteReplace#3]
Not sure if you want docs downloaded with an install, but I am guessing not, so you need to add it to .gitignore, or via .gitattributes using: `docs export-ignore`

**Comment by rolandtoth** [comment]
I think it doesn't hurt if the docs are available from the module's folder (even if only in pure readme files). Is there anything against it besides the extra number of files? It's only about 60 kbytes altogether.

**Comment by adrianbj** [comment]
I guess it's not a big deal - just perhaps a little confusing to someone who tries to open the index.html which won't work locally.

Anyway, just wanted to point it out in case you'd overlooked it :)
